### ISSUE TITLE
Good Work :D

### ISSUE THREAD

**Issue by alexisvincent** [palmerhq/backpack#11]
We need stuff like this in the JS build ecosystem so keep up the good work :D 
I'm building [systemjs-tools](https://github.com/alexisvincent/systemjs-tools#automatic-configuration-and-smart-defaults) which is in a similar space but for the SystemJS ecosystem.

**Comment by jaredpalmer** [comment]
Thanks for the props! Let me know if you have any suggestions about how to improve Backpack

**Comment by malexdev** [comment]
@jaredpalmer Didn't want to clutter you with a new issue, but seriously, good work. This looks great.
Especially thanks so much for making a default configuration. One of the most annoying things about Webpack and Babel is the fact that you must configure it every time.
