### ISSUE TITLE
add node debug support

### ISSUE THREAD

**Issue by yegor-sytnyk** [palmerhq/backpack#19]
would be nice to be able to attach to node process and specify debug port (maybe nodeDebug (number) option in package.json, if present in dev mode node is run with specified debug port or default one 5858) 

can be implemented passing --debug={portNumber} to nodemon

```JavaScript
...
nodemon({ script: mainPath, watch: serverPaths, flags: [], nodeArgs: [`--debug=${portNumber}`] })
...
```

**Comment by jaredpalmer** [comment]
Yup. 

This shouldn't be too difficult to add. Just need to parse `args` and feed them to `nodemon`.

**Comment by jyanchen** [comment]
why I still can not debug? I also add '--debug=5858'.

**Comment by lukeshiels** [comment]
@jyanchen in newer versions of Node the `--debug` flag is replaced with the `--inspect` flag.

**Comment by jyanchen** [comment]
@lukeshiels In some reasons, I'am still using V6.10.3. Now, I can use `--inspect` to debug, but no network panel, so I want to use node-inspector, but it seems not work
