### ISSUE TITLE
Built project, dependency error

### ISSUE THREAD

**Issue by malexdev** [palmerhq/backpack#25]
I installed backpack via `yarn add backpack-core --dev` as the docs stated, and added build scripts as described to `package.json`.

I then built my program via `yarn run build`, removed my `node_modules` folder, and reinstalled with `yarn --production`.

I then ran `node build/main`, and this immediately failed because I was missing the module `use-source-maps`, which Webpack had required at the start of the built script.

Of course, with `backpack-core` installed, this is not an issue.
Could we please either amend the docs to say to install `backpack-core` as a full on dependency, or (preferred) direct Webpack to not generate sourcemaps when running `backpack build`?

My opinion on that is, when I'm running backpack in a dev environment, I want source maps to be there. However when I'm running in production, I no longer care about source maps, so I'd rather not have the (comparatively massive) dependencies of Babel and Webpack hanging around for something I don't care about. I assume this is your opinion too, since you want backpack to be installed via `--save-dev`.

Of course I know that I can manually configure these options (and plan to do so if necessary), but I love the concept of this package being easy to use and having sensible defaults.

Thanks for your time!

**Comment by holmesal** [comment]
I just ran into this as well. 

I'm actually kinda surprised that I haven't seen more complaints about this. Shouldn't this affect everyone that follows the instructions (install as a dev dependency, build for production w/ defaults)?

**Comment by jaredpalmer** [comment]
Moved it to regular dep in the readme. This basically will depend on whether you want/use source-maps in production. Will update the examples now.

**Comment by jaredpalmer** [comment]
We've also been using this mostly on heroku, so we usually just throw everything into dependencies anyway.

**Comment by jaredpalmer** [comment]
cross-spawn will also throw an error, after yarn --production.

**Comment by cdimascio** [comment]
it is beneficial to install backpack as a dev dependency. for example, it saves a good amount on disk space. backpack pulls in a number of deps including babel which are not needed at runtime.

currently, backpack can be installed as a dev dependency using the following workaround.
```
npm install backpack --save-dev
npm install source-map-support cross-spawn --save
```

**Comment by tobiasbueschel** [comment]
@cdimascio @jaredpalmer is the following still the recommended way to install Backpack as a devDependency?

```
npm install backpack --save-dev
npm install source-map-support cross-spawn --save
```

Thanks :)
