### ISSUE TITLE
Webpack alias doesn't work

### ISSUE THREAD

**Issue by Vija02** [palmerhq/backpack#33]
Hi there, I tried to alias through webpack but it doesn't seem to work. Here's my config

backpack.config.js
```
module.exports = {
  webpack: (config) => {
    config.resolve.alias = {
      "react": "preact-compat"
    }
    return config
  }
}
```
Please take a look at it, Thanks!

**Comment by jaredpalmer** [comment]
So I don't suggest using react or preact with this kit yet. It will work, but you won't get things like hot loading working the way u would like them too. However, i am working on a PR now that will support this, so stay tuned.
