### ISSUE TITLE
[idea] work with electron builds

### ISSUE THREAD

**Issue by samjbmason** [palmerhq/backpack#51]
This may be out of the scope of the project, but it would be great if this worked with electron.

**Comment by jaredpalmer** [comment]
I like this. I have a minimal electron boilerplate I've used in the past (mostly for Framer.js prototyping). It uses webpack-dev-server under the hood, where as backpack uses vanilla webpack at the moment. 

However, I am considering actually downsizing backpack-core's footprint to basically just a shell runner and base webpack config. Then the plan would be to publish a small handful of modules that would augment the base config for various use-cases. For example, there could be`backpack-target-react-spa` or `backpack-target-react-iso`, `backpack-target-electron`. 

In this universe, then you would just do something like:

```js
//backpack.config.js
module.exports = require('backpack-target-electron')
```

As long as we build cli bootstraps the template (like CRA does), does anyone care that there are two modules vs. one module installed? Not really imho. Plus we could make it something like `backpack init --electron myApp`. #showerthoughts.

**Comment by samjbmason** [comment]
Hey Jared, that's some good shower thoughts! I would agree I really like the approach of making backpack be the basic runner and composing with these target modules. I don't think users would mind as long as it's clearly documented and even better if there is an init command.
