### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by InvertedX** [palmerhq/backpack#59]
```
module.js:442
    throw err;
    ^

Error: Cannot find module 'F:\Main Projectes\NUXT\"F:\Main '
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```
this weird bugging for days .i started a project with nuxt and i cloned fresh nuxt template and i tried to run  dev server and getting this error.

i tried build and it woks fine . but only dev server not working 
i am running on windows 10 and reinstalled my OS and this error! its  still there 

i am running on windows 10 
NODE  v6.3.1
NPM 5.0.3

**Comment by InvertedX** [comment]
i think backpack not executing main.js file in the build directory that's why it's throwing module not found error . so i did this. i run one terminal with **backpack dev** and still i can see the error and then i used another terminal  and navigated to build directory and executed  js file with **nodemon**  and it works

**Comment by InvertedX** [comment]
finally i found it.. this is happening because my directory contains white-spaces . i removed white-space  and it works .

**Comment by abesamiskevin** [comment]
I'm running into the same problem and the file directory that I'm running my project from has white-space too.

Shouldn't this be able to work from any type of directory, regardless of whether or not it has white-space?
