### ISSUE TITLE
Migrate to Webpack 3.x

### ISSUE THREAD

**Issue by fibric** [palmerhq/backpack#66]
Webpack 3 was released, and they want to publish new versions more often. A pull request exists #60

Is it wanted to follow the release process of Webpack? What are the criteria to choose when to upgrade and to which Webpack version?

**Comment by jaredpalmer** [comment]
See 0.4.0. Just published.

**Comment by v1adko** [comment]
@jaredpalmer Does it mean that readme is outdated?
https://github.com/jaredpalmer/backpack/blame/master/README.md#L15
It says webpack 2. Need a PR?
