### ISSUE TITLE
Readme should include lyrics...

### ISSUE THREAD

**Issue by resistdesign** [palmerhq/backpack#8]
The readme should include the lyrics to the backpack song from Dora the Explorer.

**Comment by jaredpalmer** [comment]
<img width="577" alt="screen shot 2017-01-12 at 3 46 50 pm" src="https://cloud.githubusercontent.com/assets/4060187/21907660/6a6beb4e-d8de-11e6-9efa-4e74da3fe273.png">

**Comment by resistdesign** [comment]
Perfect!
