### ISSUE TITLE
Custom entry point

### ISSUE THREAD

**Issue by sebasgarcep** [palmerhq/backpack#9]
Are there any ways to define custom entry points other than `src/index.js`?

**Comment by jaredpalmer** [comment]
Yup. See the example: https://github.com/palmerhq/backpack/blob/master/packages/backpack-examples/with-custom-webpack-config/backpack.config.js#L9

**Comment by sebasgarcep** [comment]
Link is broken. This is the right one. https://github.com/palmerhq/backpack/blob/master/examples/with-custom-webpack-config/backpack.config.js#L9.

**Comment by jaredpalmer** [comment]
Yeah I moved the examples to the top level directory
